name: Markdown link check

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: mlc_config.json
  notify-build-failure:
    needs: [markdown-link-check]
    if: failure()
    uses: AlgoAITech/meta-repo/.github/workflows/notify-ci-failure-callable.yml@master
    secrets: inherit

